### ISSUE TITLE
Current Snark worker fee for a snarker panel wrong metric

### ISSUE THREAD

**Issue by garethtdavies** [dsrvlabs/coda-performance-dashboard#10]
Currently this panel uses the `Coda_Scan_state_snark_fees_per_block` Prometheus metric which isn't correct. This metric is only available via GraphQL:

```
query snarkWorkerFee {
  currentSnarkWorker {
    fee
  }
}
```

**Comment by jongkwang** [comment]
thank you. @garethtdavies 😄 

Testnet 3.3 has ended and is difficult to test.
I wonder how you test it.
(Sandbox node didn't work. How about?)

**Comment by garethtdavies** [comment]
I added this to my setup which is using the sandbox. I didn't test with the node exporter plugin but just the mina(coda) metrics. Here's the relevant part of my compose file that I'm using - you can then use as a source for GraphQL plugin (Server) `http://coda:3085/graphql`.

```
version: "3.7"
services:
    coda:
        image: codaprotocol/coda-demo:0.0.16-beta7-debug-adding-ledger-catchup-logs-4398f6e
        ports:
            - "3085:3085"
            - "8302:8302"
            - "5001:5001"
        restart: always
        command: -metrics-port 5001
    prometheus:
        image: prom/prometheus
        volumes:
            - type: bind
              source: ./prometheus.yml
              target: /etc/prometheus/prometheus.yml
            - prom-storage:/prometheus
        ports:
            - 9090:9090
        restart: always
    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes:
            - grafana-storage:/var/lib/grafana grafana/grafana
        environment:
            - GF_INSTALL_PLUGINS=fifemon-graphql-datasource
        restart: always
volumes:
    grafana-storage:
    prom-storage:
```

and the `.prometheus.yml` file:

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'coda'

rule_files:

scrape_configs:

  - job_name: 'coda'
    static_configs:
      - targets: ['coda:5001']
```
